service: dictionaryserver
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:535486190749:table/Dictionary

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

custom:
  bundle:
    linting: false
